end_animation: {name: Wipe}
geo: {api_key: !!python/unicode 'AIzaSyCyCLvLMJooiqM_FEeSQf8bAYaDmOEEMps', default_latitude: !!python/unicode '51.7457',
  default_longitude: !!python/unicode '2.2178', enabled: !!python/unicode 'on', location: !!python/unicode 'Stroud
    UK', time_zone: Europe/London}
motion: {timeout: 3}
start_animation: {name: Fade}
strip:
  active_color: {B: 200, G: 40, R: 40}
  brightness: 40
  channel: 0
  count: !!python/unicode '31'
  dma: 5
  frq: 800000
  invert: false
  max_brightness: 180
  night_brightness: !!python/unicode '22'
  pin: !!python/unicode '18'
